version: '3'

services:
  dbnd:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:airflow@postgres/airflow
      - AIRFLOW__CORE__PARALLELISM=4
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__DAGS_FOLDER=/dbnd/examples/src/dbnd_examples/dbnd_airflow
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./modules/:/dbnd/modules/
      - ./plugins/:/dbnd/plugins/
      - ./.dbnd/airflow/dags/:/root/airflow/dags/

  postgres:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - /dev/urandom:/dev/random   # Required to get non-blocking entropy source
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"

volumes:
  database-data: # named volumes can be managed easier using docker-compose
