# Requirements:
# * make dist
# * make kaniko/int-webserver

version: "3.7"

services:
  # HDFS services
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop.env
  #     Ensure namenode leaves safe mode to prevent test breakage
  #    command: hadoop dfsadmin -safemode leave && bash -c "/run.sh"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    ports:
      - 9864:9864
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - hadoop.env

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - hadoop.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - hadoop.env

  inttest:
    image: ${DOCKER_IMAGE_INT_WITH_PLUGINS:-gcr.io/dbnd-dev-260010/databand:dbnd-int-with-plugins-py36-local}
    depends_on:
      - databand_database
      - namenode
      - datanode
      - resourcemanager
      - nodemanager1
      - historyserver
    volumes:
      - ../junit:/app/junit
      - .:/app/integration-test
    environment:
      - PYTEST_ADDOPTS=--junit-xml junit/inttest-hdfs_local_access_int_test-${IMAGE_EXTRA_TAG}.xml
      - DBND_HOME=/app/integration-test
    working_dir: /app/integration-test
    command:
      - bash
      - -c
      - |
        airflow initdb
        pytest . -vv

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
